name: React CI/CD

# Trigger workflow on push or pull request to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Run tests
      run: npm test --if-present

    # Optional deployment to server
    - name: Deploy to Oracle Linux server
      if: github.ref == 'refs/heads/main'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: root
        SERVER_HOST: 10.1.14.101
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        rsync -avz -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" ./build/ $SERVER_USER@$SERVER_HOST:/var/www/myapp/
